### ISSUE TITLE
Ranger Forest Classifier, Python: how to access the predictions of each tree separately?

### ISSUE THREAD

**Issue by selinakiefer** [crflynn/skranger#152]
Hi,
if I understand it correctly, in order to be able to access the predictions of each tree of the Ranger Forest Classifier, "enable_tree_details" has to be set "True" (https://skranger.readthedocs.io/en/stable/ranger_forest_classifier.html). 

When I do this:

**from** skranger.ensemble **import** RangerForestClassifier
random_forest_classifier = RangerForestClassifier(enable_tree_details=True)

I get the following error message:

TypeError: __init__() got an unexpected keyword argument 'enable_tree_details'

I am using Python.

Did I do something wrong or is there any other way to access the predictions of each tree separately? 

I would really appreciate your help!

Kind regards
Selina

**Comment by crflynn** [comment]
Are you using a version >=0.6.0?
