### ISSUE TITLE
Extract variable importance scores

### ISSUE THREAD

**Issue by bgreenwell** [crflynn/skranger#57]
Hey @crflynn , thanks for porting **ranger** over to Python. Is there a way to extract the variable importance scores from the fitted forest object?

**Comment by crflynn** [comment]
After fitting there is an instance attribute named `ranger_forest_` that is a dictionary of everything passed back from ranger. It is a bit informal but you should be able to extract it from there.

**Comment by bgreenwell** [comment]
A colleague of mine just found it:

```python
rfo.ranger_forest_['variable_importance']
```

**Comment by bgreenwell** [comment]
Is there any plan to include/expose ranger's `importance_pvalues()` funcction?

**Comment by crflynn** [comment]
https://github.com/imbs-hl/ranger/blob/e8b05f47892bb4968c4e6057f68b35bcd0b52225/R/importance.R

Looks like it's just pure R code here? Feel free to create another issue as a feature request and I can take a look at it.
