### ISSUE TITLE
sample_fraction, 'float' object is not iterable

### ISSUE THREAD

**Issue by dalekube** [crflynn/skranger#58]
While defining the RangerForestRegressor with `rfr = RangerForestRegressor(n_estimators=150, oob_error=False, verbose=True, sample_fraction=0.50)`, the error `'float' object is not iterable` is produced.

The help docs for the class do not specify a type for `sample_fraction`, but it's implied that it should accept float values like 0.50, similar to what is accepted in the R equivalent:

 |  :param sample_fraction: The fraction of observations to sample. The default is 1
 |      when sampling with replacement, and 0.632 otherwise. This can be a vector of
 |      class specific values.

I'm using Python 3.8.5.

**Comment by crflynn** [comment]
You should be able to fix this locally with this change until I make a new release.

https://github.com/crflynn/skranger/pull/59/files#diff-501571553535d8cc166fda2d1904b6b00f309e993173325f3119051ba6a42c40

**Comment by dalekube** [comment]
Great, thanks for the temporary solution.
