### ISSUE TITLE
Error when adding split_select_weights

### ISSUE THREAD

**Issue by smantz** [crflynn/skranger#88]
I tried to add a list of weights to the `RangerForestRegressor` by using the parameter `split_select_weights` like this:
```python
treeEstimator = RangerForestRegressor(split_select_weights=weight_list)
treeEstimator.fit(X_train, y_train)
```
Now I get the following error message (which does not appear, if I use this without the `split_select_weights`):
```
line 194, in fit
  self.ranger_forest_ = ranger.ranger(
  File "skranger/ensemble/ranger.pyx", line 74, in skranger.ensemble.ranger.ranger
  File "stringsource", line 48, in vector.from_py.__pyx_convert_vector_from_py_std_3a__3a_vector_3c_double_3e___
  File "stringsource", line 47, in vector.from_py.__pyx_convert_vector_from_py_double
TypeError: 'float' object is not iterable
```
Am I doing something wrong or is this a problem in the code?
(I'm new to programming, so sorry in advance if this is just a stupid mistake of me and thanks in advance!)

**Comment by crflynn** [comment]
I think that's a bug here. Looks like I'm also missing a test for this parameter. I'll try to get it fixed soon.

**Comment by smantz** [comment]
Thank you very much!

**Comment by crflynn** [comment]
try 0.4.1
